"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

DATA_DIR = "data"

DATA_FILES = []
for dirpath, dirnames, filenames in os.walk(DATA_DIR):
    # skip hidden files/directories if you want
    filenames = [f for f in filenames if not f.startswith('.') and not f.startswith('~')]
    if not filenames:
        continue
    # destination path where files will be installed, e.g. share/yourproject/data/...
    dest = os.path.join('share', os.path.basename(os.getcwd()), os.path.relpath(dirpath, DATA_DIR))
    # full source paths
    files = [os.path.join(dirpath, f) for f in filenames]
    DATA_FILES.append((dest, files))

APP = ['ATP_Prod.py']
# Ensure py2app includes certain modules that its finder can miss (e.g. cmath)
OPTIONS = {
    'includes': ['cmath'],
    # include full packages so py2app bundles them into the standalone app
    'packages': ['pandas', 'numpy', 'matplotlib', 'openpyxl'],
    # # Icon file for the .app (must be an .icns file). Create/app_icon.icns in the data folder and
    # py2app will embed it as the application icon.
    'iconfile': os.path.join('data', 'app_icon.icns'),
    # Build for both Intel and Apple Silicon
    'arch': 'universal2',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
