"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

DATA_DIR = "data"

DATA_FILES = []
for dirpath, dirnames, filenames in os.walk(DATA_DIR):
    # skip hidden files/directories if you want
    filenames = [f for f in filenames if not f.startswith('.') and not f.startswith('~')]
    if not filenames:
        continue
    # destination path where files will be installed, e.g. share/yourproject/data/...
    dest = os.path.join('share', os.path.basename(os.getcwd()), os.path.relpath(dirpath, DATA_DIR))
    # full source paths
    files = [os.path.join(dirpath, f) for f in filenames]
    DATA_FILES.append((dest, files))

APP = ['ATP_Prod.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
